<?php
return array(
	'achievement' => array('label' => 'Достижения'),
	'action'      => array('label' => 'Кнопки на панелях'),
	'bind'        => array('label' => 'Бинды'),
	'bag'         => array('label' => 'Вещи в сумках'),
	'bank'        => array('label' => 'Вещи в банке'),
	'criterias'   => array('label' => 'Критерии'),
	'critter'     => array('label' => 'Спутники'),
	'currency'    => array('label' => 'Валюта'),
	'equipment'   => array('disabled' => 1, 'label' => 'Наборы экипировки'),
	'glyph'       => array('label' => 'Символы'),
	'inventory'   => array('label' => 'Инвентарь'),
	'mount'       => array('label' => 'Транспорт'),
	'pmacro'      => array('disabled' => 1, 'label' => 'Макросы'),
	'quest'       => array('label' => 'Задания'),
	'questlog'    => array('label' => 'Журнал заданий'),
	'reputation'  => array('label' => 'Репутация', ),
	'skill'       => array('label' => 'Навыки (профессии)'),
	'skillspell'  => array('label' => 'Рецепты'),
	'spell'       => array('label' => 'Заклинания'),
	'statistic'   => array('label' => 'Статистика'),
	'talent'      => array('label' => 'Таланты'),
	'taxi'        => array('label' => 'Перелеты'),
	'title'       => array('label' => 'Звания'),
);
