<?php
return [
	'achievement' => [],
	'action'      => [],
	'bind'        => [],
	'bag'         => [],
	'bank'        => [],
	'criterias'   => [],
	'critter'     => [],
	'currency'    => [],
	'equipment'   => ['disabled' => 1],
	'glyph'       => [],
	'inventory'   => [],
	'mount'       => [],
	'pmacro'      => ['disabled' => 1],
	'quest'       => [],
	'questlog'    => [],
	'reputation'  => [],
	'skill'       => [],
	'skillspell'  => [],
	'spell'       => [],
	'statistic'   => [],
	'talent'      => [],
	'taxi'        => [],
	'title'       => [],
];
