<?php
return array(
	'achievement' => array(),
	'action'      => array(),
	'bind'        => array(),
	'bag'         => array(),
	'bank'        => array(),
	'criterias'   => array(),
	'critter'     => array(),
	'currency'    => array(),
	'equipment'   => array('disabled' => 1),
	'glyph'       => array(),
	'inventory'   => array(),
	'mount'       => array(),
	'pmacro'      => array('disabled' => 1),
	'quest'       => array(),
	'questlog'    => array(),
	'reputation'  => array(),
	'skill'       => array(),
	'skillspell'  => array(),
	'spell'       => array(),
	'statistic'   => array(),
	'talent'      => array(),
	'taxi'        => array(),
	'title'       => array(),
);
